### ISSUE TITLE
PHP demo request

### ISSUE THREAD

**Issue by nomentsoa-andrianjatovo** [isszz/rotate-captcha#3]
Can you provide a vanilla PHP+vanilla JS working demo please?
I've spent hours trying to make it work but failed

**Comment by isszz** [comment]
PHP also provides a way to use it without relying on any framework.
please read README.md carefully.

Native JS provides DEMO, you can take a look at 
[](https://github.com/isszz/rotate-captcha/blob/main/js/captcha.js)

**Comment by nomentsoa-andrianjatovo** [comment]
I've used RVerify instead, much easier to implement
